name: pet-dev
services:
  # Модули
  publisher:
    build:
      context: ./publisher
    container_name: publisher
    ports:
      - "8001:8080"
    depends_on:
      - kafka
    networks:
      - app-network

  listener:
    build:
      context: ./listener
    container_name: listener
    ports:
      - "8002:8080"
    depends_on:
      - kafka
    networks:
      - app-network

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: "dev-cluster"
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    volumes:
      - ./.infrastructure-data/kafka:/bitnami/kafka
    networks:
      - app-network

  # Графический интерфейс кафки
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    volumes:
      - ./.infrastructure-data/kui:/etc/kafkaui
    depends_on:
      - kafka
    networks:
      - app-network

  # База данных
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./.infrastructure-data/clickhouse:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=root
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    networks:
      - app-network

  # Графический интерфейс БД
  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: ch-ui
    ports:
      - "5521:5521"
    environment:
      VITE_CLICKHOUSE_URL: "http://localhost:8123" # потому что frontend-only SPA
      VITE_CLICKHOUSE_USER: "clickhouse"
      VITE_CLICKHOUSE_PASS: "root"
    networks:
      - app-network

# Прочие настройки
networks:
  app-network:
    driver: bridge